# To fix the 'Prefer single quoted...'
#   Search for   "([^{"']*)"
#   Replace with '$1'
#
# To fix Ruby 1.9 hash syntax
#   Search for      {:(\w+) =>
#   Replace with    { $1:
#   Search for      :(\w+) =>
#   Replace with    $1:
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'lib/payment_providers/every_day/every_day.rb'
    - 'bin/setup'
    - 'bin/spring'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 119

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/RegexpLiteral:
  Description: >-
                 Use %r for regular expressions matching more than
                 `MaxSlashes` '/' characters.
                 Use %r only for regular expressions matching more than
                 `MaxSlashes` '/' character.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-r'
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Description: >-
                 Checks for ambiguous regexp literals in the first argument of
                 a method invocation without parenthesis.
  Enabled: false

Lint/EndAlignment:
  Enabled: false

ClassLength:
  Max: 300

ModuleLength:
  Max: 300

Style/EachWithObject:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

BlockDelimiters:
  Enabled: false

SpaceInsideStringInterpolation:
  Enabled: false